name: josephspeiser
favicon: null
layout_spectrum: 0.14302620780654252
typography_spectrum: 0.477151837432757
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8617426238488406
  lightness: 0.710103171877563
  saturation: 0.8658996189478785
  rhythmicContrast: 0.6151500504929572
purpose: []
